DROP DATABASE IF EXISTS blogs_dev;
CREATE DATABASE blogs_dev;

\c blogs_dev;

CREATE TABLE blogs (
id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
author TEXT NOT NULL,
image TEXT DEFAULT '',
body TEXT NOT NULL,
type TEXT,
date TEXT
);

DROP TABLE IF EXISTS users;

CREATE TABLE users(
 id SERIAL PRIMARY KEY,
 name TEXT NOT NULL
);


DROP TABLE IF EXISTS comments;

CREATE TABLE comments(
 id SERIAL PRIMARY KEY,
 blog_id INTEGER REFERENCES blogs (id),
 name TEXT NOT NULL,
 content TEXT NOT NULL,
 date TEXT NOT NULL
);